from pathlib import Path
import os,shutil
r=Path(os.getenv('ATLAS_R4_ROOT',str(Path(__file__).resolve().parent.parent)));src=Path(os.getenv('ATLAS_R3_SITE',str(r.parent/'atlas_d_engineering_r3/live')));site=r/'site';site.mkdir(exist_ok=True)
for f in ['runtime.js','THIRD_PARTY_LICENSE.txt','style.css']:shutil.copy(src/f,site/f)
s=(src/'viewer.js').read_text().replace('ATLAS_D_R3.glb','ATLAS_D_R4.glb').replace('revision:3','revision:4')
s=s.replace('let ready=false,','let stopAt=null;let ready=false,')
s=s.replace('hero:[[0,7+y,0],[87,24,22]','hero:[[0,7+y,0],[87,24,25]')
s=s.replace('profile:[[0,6+y,0],[88,24,18],[0,.08,1]],','profile:[[0,8+y,0],[87,25,24],[0,.12,1]],mechanism:[[0,11+y,0],[42,16,14],[.2,.6,1.5]],stern:[[-31,4.5+y,0],[19,11,24],[-.9,.7,1.4]],')
s=s.replace('Upper pavilions are floodable, surface-only spaces—not ordinary yacht rooms underwater.','Upper rooms have been replaced by open leisure canopies. Only unoccupied exterior hardware folds; the proposed dry core stays fixed.')
s=s.replace("['Stow surface fittings','Guardrails and mast fold. Pool covers are fairings, not pressure seals.']","['Transform the exterior','Daybeds and radar fold; constant-length scissor supports lower the two canopy roofs. Side terraces fold in; the aft fairing closes.']")
s=s.replace('if(playing){pose(p+direction*dt/42);if(p>=1||p<=0)','if(playing){pose(p+direction*dt/42);if(stopAt!==null&&p>=stopAt){pose(stopAt);playing=false;stopAt=null;ui()}if(p>=1||p<=0)')
s=s.replace('function reset(){playing=false;','function reset(){stopAt=null;playing=false;')
s=s.replace("$('#play').onclick=()=>{","$('#play').onclick=()=>{stopAt=null;")
s=s.replace("$('#force').innerHTML=(dp*100).toFixed(0)+' <small>kN</small>';","$('#roofdrop').innerHTML=(5.16*smooth(.28,.54,p)).toFixed(2)+' <small>m</small>';")
s=s.replace("$('#play').textContent=playing?'Pause':p>=1?'Replay dive':p===0?'Start dive':'Continue';","$('#play').textContent=playing?'Pause':p>=1?'Replay dive':p>=.60?'Dive':'Full sequence';$('#transform').textContent=playing&&stopAt!==null?'Transforming…':'Transform only';if(!playing&&Math.abs(p-.62)<.003){$('#stage').textContent='Dive-ready silhouette · held above water';$('#detail').textContent='Compare the lower roofline, folded terraces and closed aft deck. The same hull and pressure core are still here.';}")
insert="""
$('#transform').onclick=()=>{reset();if(xray)setXray(false);setView('profile');stopAt=.62;play(1)};
$('#compare').onclick=()=>{const next=p>.3?0:.62;reset();if(xray)setXray(false);pose(next);setView('profile')};
"""
s=s.replace('setView();\nfunction fail(e)',insert+'\nsetView();\nfunction fail(e)')
s=s.replace('renderer.shadowMap.needsUpdate=true;}','renderer.shadowMap.needsUpdate=!playing;}')
(site/'viewer.js').write_text(s)
h=(src/'index.html').read_text().replace('REVISION 03','REVISION 04').replace('/ 03 — Pressure Boundary Study','/ 04 — Transforming Exterior')
h=h.replace('A yacht above.<br>A pressure vessel within.','One vessel.<br>A visibly different silhouette.').replace('Continuous-vessel study','Articulated exterior study')
h=h.replace('<label>LOAD / 1 m²*</label><strong id="force">0 <small>kN</small></strong>','<label>CANOPY ROOF DROP</label><strong id="roofdrop">0 <small>m</small></strong>')
h=h.replace('<button id="play" class="primary">Start dive</button>','<button id="transform" class="primary">Transform only</button><button id="compare">Before / Ready</button><button id="play">Full sequence</button>')
h=h.replace('<button data-view="seals">Seals</button>','<button data-view="mechanism">Canopies</button><button data-view="stern">Stern</button>')
h=h.replace('02 Stow','02 Fold').replace('03 Isolate','03 Lower').replace('04 Flood','04 Ready').replace('data-step=".60"','data-step=".62"')
h=h.replace('Inspect the pressure boundary, then follow the closures, vents and ballast before descent.','Choose Transform only: the roofline drops, terraces fold and the aft shell closes BEFORE the boat descends.')
h=h.replace('The lower pressure capsule is the proposed dry enclosure. Upper pavilions are floodable, surface-only spaces—not ordinary yacht rooms underwater.','The lower pressure core stays fixed. The former upper enclosures have been redesigned as open, surface-only leisure canopies. They fold only after the area is cleared.').replace('Floodable pavilions','Wet exterior spaces')
(site/'index.html').write_text(h)
with open(site/'style.css','a') as f:f.write('\n.primary-controls{flex-wrap:wrap}#transform{font-weight:700}#compare{border-color:#c0d8c7}@media(max-width:650px){.toolbar{gap:5px}.primary-controls{gap:4px}.primary-controls button{font-size:11px;padding:9px 9px}.stages{font-size:9px}header p{max-width:205px}}\n')
(site/'design.html').write_text('''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATLAS D R4 design decisions</title><style>body{font:17px/1.65 system-ui;background:#102832;color:#edf5f3;max-width:840px;padding:30px;margin:auto}a{color:#bfe1cb}h1{font-weight:500}strong{color:#bddac9}</style><a href="index.html">← Interactive model</a><h1>Revision 04 — a visible conversion</h1><p><strong>Design change, not an animation trick:</strong> the previous upper enclosed rooms and roof decks are replaced in this variant by two OPEN leisure canopies over one fixed terrace. Those occupied volumes do not collapse or shrink during playback; they are no longer part of this design.</p><h2>What moves</h2><p>Daybed backs fold flat. The radar folds onto the forward roof. Fixed-length scissor links lower the sculpted canopies. Side terraces rotate into exterior casing panels. Linked rigid fairing slats roll from a modeled cassette over the aft pool terrace. Roofs, mechanism bars and exterior panels retain their dimensions.</p><p>The forward canopy roof drops 5.16 m. This is non-pressure structure: nobody may remain in its closure envelope. Scissor guides, pivots and mounting locations illustrate paths, but hinge loads, hydraulics, tolerances, collision/clearance verification and structural redundancy are unresolved.</p><h2>What stays fixed</h2><p>The main hull meshes and lower candidate pressure capsule from R3 are unchanged. The capsule remains a geometric arrangement without pressure-shell thickness, verified viewports, qualified hatches or a depth rating. Outer covers are not pressure seals.</p><h2>How to see the difference</h2><p>Transform only runs the conversion and holds at the surface. Before / Ready alternates configurations from the same profile view. Canopies and Stern show close-ups. Full sequence continues through the inherited illustrative dive.</p><h2>Scientific boundary</h2><p>Separating a fixed pressure hull from floodable outer casing is established submarine architecture. This does not validate these moving canopies. The 40 m descent is prescribed kinematics, not a buoyancy/dynamics simulation or allowed depth. Pressure, mass, stability, energy, fatigue, sealing, recovery and sea-state operation remain unverified.</p><p><a href="https://maritime.org/doc/oberon/principles/index.php">Source: Canadian submarine principles manual — pressure hull, casing and ballast</a>. This source does not review or endorse ATLAS D.</p><h2>Next gate</h2><p>Audit stowage paths and pinch points, then complete an arrangement and mass study before claims of hydrodynamic performance or physical operability. This revision tests whether mechanically legible transformation can deliver the desired visual change.</p></html>''')
