/* R9: selected measured repairs and arrangement screens, not safety-rated controls or validated vessel dynamics. */
(()=>{'use strict';
const T=window.ATLASRuntime,$=s=>document.querySelector(s),V=(...a)=>new T.Vector3(...a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let ready=false,model,vessel,report,meshes=[],bindings=[],progress=0,playing=false,mode='exterior',showPressure=true,planView=false,dirty=true,last=performance.now(),labels=[],mass=null,floods=0,legacy=false,playEnd=.8;
const mobile=innerWidth<751;
try{
const renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.25:1.65));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;
const scene=new T.Scene();scene.background=new T.Color('#c5d4d8');scene.fog=new T.Fog('#c5d4d8',300,1800);
const camera=new T.PerspectiveCamera(31,1,.1,3000),controls=new T.OrbitControls(camera,$('#scene'));controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=3;controls.maxDistance=650;controls.maxPolarAngle=Math.PI*.96;controls.addEventListener('change',()=>{dirty=true});
const ew=256,eh=128,envdata=new Uint8Array(ew*eh*4);for(let yy=0;yy<eh;yy++)for(let xx=0;xx<ew;xx++){let t=yy/(eh-1),a=t<.5?[.35+.85*t,.47+.67*t,.57+.48*t]:[.25-.25*(t-.5),.35-.33*(t-.5),.39-.38*(t-.5)],i=(yy*ew+xx)*4;for(let k=0;k<3;k++)envdata[i+k]=Math.min(255,a[k]*255);envdata[i+3]=255}const env=new T.DataTexture(envdata,ew,eh);env.mapping=303;env.colorSpace=T.SRGBColorSpace;env.needsUpdate=true;const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromEquirectangular(env).texture;pm.dispose();env.dispose();scene.environmentIntensity=.8;
scene.add(new T.HemisphereLight(0xeff7ff,0x566a6a,1.6));const sun=new T.DirectionalLight(0xffefdc,2.4);sun.position.set(-40,65,50);scene.add(sun);const fill=new T.DirectionalLight(0xd3edf7,1.1);fill.position.set(30,10,-50);scene.add(fill);
const water=new T.Mesh(new T.PlaneGeometry(3000,3000),new T.MeshStandardMaterial({color:0x497785,roughness:.33,metalness:.15,side:T.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=.01;scene.add(water);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();dirty=true}addEventListener('resize',()=>{resize();frameView()});resize();
function group(o){let n=o;while(n.parent&&n.parent!==vessel&&n.parent!==model)n=n.parent;return n.name}
function fit(center,size,vector){const t=V(...center),d=V(...vector).normalize(),up0=mobile&&(mode==='upper'||mode==='lower')?V(1,0,0):planView?V(0,0,-1):V(0,1,0);camera.up.copy(up0);const right=up0.clone().cross(d).normalize(),up=d.clone().cross(right).normalize();const tan=Math.tan(camera.fov*Math.PI/360);let dist=0;for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1]){const q=V(x*size[0]/2,y*size[1]/2,z*size[2]/2);dist=Math.max(dist,Math.abs(q.dot(right))/(tan*(!mobile&&['exterior','upper','lower','buoyancy'].includes(mode)?(innerWidth-350)/innerHeight:camera.aspect))+q.dot(d),Math.abs(q.dot(up))/tan+q.dot(d))}camera.position.copy(t).addScaledVector(d,dist*1.14);controls.target.copy(t);camera.setViewOffset(innerWidth,innerHeight,mobile?0:135,mobile?30:30,innerWidth,innerHeight);camera.updateProjectionMatrix();controls.update();dirty=true}
function frameView(){const y=ready?vessel.position.y:0;let center=[0,6+y,0],size=[86,24,22],dir=mobile?[1.4,.8,1.2]:[.5,.35,1.4];if(mode==='upper'||mode==='lower'){center=[2.5,(mode==='upper'?1.8:-.5)+y,0];size=[54,11,13];dir=[.1,1.1,1.1]}if(mode==='recovery'){center=[-40,2+y,0];size=[34,12,25];dir=[-1,.6,1.25]}if(mode==='pool'){center=[-31,4+y,0];size=[20,11,14];dir=[-.5,.45,1.5]}if(mode==='garages'){center=[-32.5,2.4+y,0];size=[20,8,12];dir=[-1,.7,1.3]}if(mode==='buoyancy'){center=[-3,.9+y,0];size=[76,12,18];dir=[.15,.65,1.4]}if(planView)dir=[.001,1,.001];fit(center,size,dir)}
function visible(){if(!ready)return;for(const m of meshes){const b=m.userData.base,g=m.userData.group;let a=b.opacity,on=false;
 if(g.startsWith('ENG_')){if(mode!=='exterior'){
 if(g==='ENG_Pressure'){on=showPressure&&(mode!=='garages');a=m.material.name==='Candidate pressure envelope'?.12:.45}
 if(g==='ENG_Upper')on=mode==='upper';if(g==='ENG_Lower')on=mode==='lower';if(g==='ENG_Rooms')on=mode==='upper'||mode==='lower';
 if(g==='ENG_Garages'){on=['garages','buoyancy','pool','recovery'].includes(mode);a=m.material.name==='Candidate tender pressure pods'?.18:b.opacity}
 if(g==='ENG_PreviousCradles'){on=legacy&&mode==='garages';a=.38}if(g==='ENG_Clearances')on=false;if(g==='ENG_Dimensions')on=false;
 }}else if(mode==='exterior'){on=!g.startsWith('SYS_')&&g!=='FX_Subsea_light_beams'}else{
 if(g==='FIXED_Hull'){on=true;a=.035}if(['garages','recovery'].includes(mode)&&(g.startsWith('MOV_Tender')||g.startsWith('MOV_Cradle'))){on=true;a=1}
 }
 if(mode==='pool'&&g==='FIXED_Main_deck'&&['tile','white','water','chrome','Raised pool access treads'].includes(m.material.name)){on=true;a=m.userData.base.opacity;}
 if(b.color)m.material.color.copy(b.color);
 m.visible=on;m.material.opacity=a;m.material.transparent=b.transparent||a<.999;m.material.depthWrite=b.depthWrite&&a>.95;m.material.needsUpdate=true;
 }water.visible=mode==='exterior';$('#legacy').hidden=mode!=='garages';$('#legacy').setAttribute('aria-pressed',String(legacy));$('#pressure').setAttribute('aria-pressed',String(showPressure));makeLabels();dirty=true}
function label(text,point,cl=''){const el=document.createElement('span');el.className='label '+cl;el.textContent=text;$('#labels').appendChild(el);labels.push({el,point})}
function makeLabels(){labels=[];$('#labels').replaceChildren();if(!report||!ready)return;
 if(mode==='upper'||mode==='lower'){
 const deck=mode==='upper'?'upper':'lower';for(const r of report.rooms){if(r.deck!==deck)continue;if(mobile&&r.type==='crew'&&!r.name.endsWith('_1'))continue;let text=r.name.replaceAll('_',' ');if(r.name.startsWith('Crew_'))text='2 crew';else if(r.name.startsWith('Guest'))text='Suite '+r.name.slice(-1)+(mobile?' · '+r.gross_reserved_area_m2.toFixed(1)+' m²':'');else if(r.name==='Owner_suite')text='Owner · 31.2 m²';else text=text.replace('reservation','').replace('Sanitary laundry','Shared wet rooms').replace('Stair and access lobby','Stair / lobby');label(text,[(r.x0+r.x1)/2,r.floor_y+1.18,(r.z0+r.z1)/2])}
 if(!mobile)label('41.0 m fixed deck · 6.1 m planning width',[2.5,mode==='upper'?3.7:1.3,-4.2],'dim');
 }else if(mode==='garages'){
 label('Unscaled chase tender + replacement carrier',[-33.7,3.9,2.5]);label('Unscaled utility tender + replacement carrier',[-33.7,3.1,-2.5]);label('Circular pressure-closure candidate',[-40.5,2.4,2.5]);
 }else if(mode==='pool'){label('Basin underside 5.05 m',[-30.5,5.05,2.5],'dim');label('Garage crown 4.75 m · 300 mm geometric gap',[-30.5,4.75,-2.5]);
 }else if(mode==='recovery'){label('Align & lift outside the opening',[-49.8,2.4,0],'dim');label('Straight insertion into each candidate bore',[-33.7,4.8,0]);
 }else if(mode==='buoyancy'){
 label('Main envelope · '+report.volumes.main_pressure_envelope_m3.toFixed(0)+' m³',[2.5,6.3,0],'dim');label('2 garage envelopes · '+(report.volumes.garages_each_outer_m3*2).toFixed(0)+' m³',[-33.5,6.8,0],'dim');
 }}
function labelsFrame(){const y=ready?vessel.position.y:0;for(const l of labels){const v=V(l.point[0],l.point[1]+y,l.point[2]).project(camera);let x=(v.x+1)*innerWidth/2,yy=(1-v.y)*innerHeight/2;const covered=!mobile&&!$('#panel').classList.contains('closed')&&x>innerWidth-340;l.el.style.left=x+'px';l.el.style.top=yy+'px';l.el.hidden=covered||v.z>1||x<12||x>innerWidth-12||yy<163||yy>innerHeight-135}}
function stat(a,b){return '<dt>'+a+'</dt><dd>'+b+'</dd>'}
function panel(){if(!report)return;const ar=report.architecture,vol=report.volumes;let title,ey,html;
 if(mode==='exterior'){
 ey='CANDIDATE, NOT A CERTIFIED VESSEL';title='Same yacht. More accountable design.';html='<p>The original helipad, layered exterior and tender-recovery animation are retained. Narrow recovery carriers replace the rejected broad platforms. The pool rises 0.42 m to clear the garage roofs. Permanent dry-room allocations remain fixed.</p><dl>'+stat('Fixed dry decks','2')+stat('Guest / crew target','12 / 24')+stat('Geometric repairs this pass','2')+stat('Remaining hard blockers','2')+'</dl><p class="warn">The animation is not evidence that this yacht can dive. Select a deck or tender view to inspect the arrangement.</p><a class="mini" href="design.html" target="_blank">Read findings & assumptions ↗</a>';
 }else if(mode==='upper'||mode==='lower'){
 ey='DIMENSIONED SPACE RESERVATIONS';title=mode==='upper'?'Permanent guest accommodation':'Crew and machinery allocations';html='<dl>'+stat('Pressure-core diameter','8.6 m')+stat('Core overall length','50.6 m')+stat('Planning deck','41.0 × 6.1 m')+stat('Reserved headroom','2.20 m')+stat('Two-deck gross area','500.2 m²')+'</dl><p>'+(mode==='upper'?'Five guest-suite reservations, an owner suite, an observation salon and command space. The 31.2 m² owner reservation includes its bathroom allocation.':'Twelve compact twin-bunk crew cabins, a machinery reservation, mess, galley, shared wet rooms and service zones.')+'</p><p class="ok">Full-height room boxes fit the analytic inner planning envelope.</p><p class="small">Low cutaway walls are used for visibility. 0.40 m is a radial planning allowance for structure/frames/services—not a designed shell thickness. Gross area includes partitions, circulation and stair space.</p><p class="warn">Berths fit as reservations; comfort, ventilation, fire separation, service access and emergency egress are not qualified.</p>';
 }else if(mode==='garages'||mode==='recovery'){
 ey='SELECTED GEOMETRIC CHECKS · NOT QUALIFICATION';title=mode==='recovery'?'Align. Lift. Insert.':'Recovered craft AND carriers';const a=report.recovery_hardware_checks[0],b=report.recovery_hardware_checks[1];html='<dl>'+stat('Candidate inner bore','4.36 m')+stat('Chase carrier radial gap',(a.minimum_radial_clearance_m*1000).toFixed(0)+' mm')+stat('Utility carrier radial gap',(b.minimum_radial_clearance_m*1000).toFixed(0)+' mm')+stat('Axial insertion samples','241 per craft')+'</dl><p class="ok">Both replacement carriers now fit the idealized bore. Complete tender geometry is unchanged.</p><p>The empty carrier extends first, lowers outside the opening, lifts the aligned tender, then slides aboard. Outer styling doors close after both transfers.</p><p><strong>Previous cradles</strong> overlays the rejected broad platforms in red at the stored pose.</p><div class="tag">STILL UNRESOLVED</div><p>Opening freeboard is only 0.22 m above the unsolved visual waterline. The exterior aperture, actual pressure doors, support loads, deflection, tolerances and complete collision paths require design.</p><p class="small">The check covers the unobstructed circular barrel only, not the whole vessel or safe recovery at sea. A positive gap is not an approved movement allowance.</p>';
 }else if(mode==='pool'){
 ey='DIMENSIONED CORRECTION';title='Pool above the garage, not through it';html='<dl>'+stat('Pool unit lift','420 mm')+stat('Basin underside','5.05 m')+stat('Candidate garage crown','4.75 m')+stat('New vertical gap','300 mm')+stat('New access treads','3')+'</dl><p class="ok">The whole pool basin, water surface and covers move upward together. Modeled water depth is retained, rather than disguising the conflict with a flattened pool.</p><p>The additional volume between pool and pods is visible in this cutaway. Covers still slide from their raised cassette.</p><p class="warn">These are geometric envelopes. Reinforcement, insulation, pipes, structural deflection, loads and local circulation still require design.</p>';
 }else{
 ey='GROSS DISPLACEMENT SENSITIVITY';title='Volume is not a completed mass budget';html='<dl>'+stat('Main sealed envelope',vol.main_pressure_envelope_m3.toFixed(1)+' m³')+stat('Two candidate garages',(2*vol.garages_each_outer_m3).toFixed(1)+' m³')+stat('Gross buoyant equivalent',vol.fully_immersed_gross_buoyant_equivalent_tonnes.toFixed(1)+' t')+'</dl><p class="small">At full immersion, ρ = 1,025 kg/m³. Floodable fairings receive no enclosed-volume credit. Immersed solid displacement and all-up mass are still unestablished.</p><button id="example">Use hypothetical 3,300 t example</button><div id="scenario" '+(mass===null?'hidden':'')+'><label>Hypothetical all-up mass: <strong id="mass-label"></strong><input id="mass" type="range" min="2400" max="4200" step="10" value="'+(mass||3300)+'"></label><label>Gross-volume loss scenario<select id="loss"><option value="0">Intact candidate envelopes</option><option value="1">Remove one garage envelope</option><option value="2">Remove both garage envelopes</option></select></label><div class="value" id="net"></div><p id="net-copy"></p></div><p class="warn">This is not the vessel\'s estimated displacement, operating ballast, reserve buoyancy or damage-stability calculation. No ascent capability follows from a positive number.</p><p class="small">Garage-loss cases subtract gross outer volume: an upper-bound sensitivity, not an exact floodable-void calculation. Heel/trim and asymmetric flooding are not solved.</p>';
 }
 $('#panel-ey').textContent=ey;$('#panel-title').textContent=title;$('#panel-content').innerHTML=html;
 if(mode==='buoyancy'){
 $('#example').onclick=()=>{mass=3300;$('#scenario').hidden=false;$('#mass').value=mass;scenario()};$('#mass').oninput=e=>{mass=+e.target.value;scenario()};$('#loss').value=floods;$('#loss').onchange=e=>{floods=+e.target.value;scenario()};if(mass!==null)scenario();
 }
}
function calc(m,n=0){const v=report.volumes;return 1.025*(v.credited_sealed_envelopes_total_m3-n*v.garages_each_outer_m3)-m}
function scenario(){if(mass===null)return;const net=calc(mass,floods);$('#mass-label').textContent=mass.toLocaleString()+' t';$('#net').textContent=(net>=0?'+':'')+net.toFixed(1)+' t';$('#net-copy').textContent=net>=0?'Gross buoyancy exceeds this hypothetical mass by the displayed equivalent. This does not prove operational balance.':'This hypothetical mass exceeds credited gross buoyancy. More ballast cannot cure a negative result.'}
function setMode(value){if(!ready)return;mode=value;playing=false;planView=false;if(mode!=='exterior')pose(mode==='recovery'?.12:.8);visible();panel();frameView();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#plan').setAttribute('aria-pressed','false');if(mobile)$('#panel').classList.add('closed');dirty=true}
function ui(){$('#pct').textContent=Math.round(progress*100)+'%';$('#timeline').value=Math.round(progress*1000);$('#play').textContent=playing?'Pause':'Transform fittings';$('#motion-note').textContent=progress>.845?'Prescribed descent only · no established safe depth, buoyancy or stability.':progress<.13?'Open / extend recovery carriers · helipad and permanent accommodation retained.':progress<.375?'Tenders align and lift outside the bores, then insert axially.':progress<.45?'Both tenders aboard · outer styling doors close. Pressure closures remain unresolved.':'Exterior shells stow · fixed dry rooms do not move. No engineering qualification.'}
function pose(value){if(!ready)return;progress=clamp(value,0,1);const prev=vessel.position.y;for(const b of bindings)b.object[b.property].fromArray(b.interpolant.evaluate(progress*48));model.updateMatrixWorld(true);const delta=vessel.position.y-prev;camera.position.y+=delta;controls.target.y+=delta;ui();dirty=true}
$('#play').onclick=()=>{if(!ready)return;if(playing){playing=false;ui();return}playEnd=mode==='recovery'?.455:.8;if(progress>=playEnd)pose(0);playing=true;last=performance.now();ui()};$('#legacy').onclick=()=>{legacy=!legacy;playing=false;pose(.8);visible()};$('#dive').onclick=()=>{if(!ready)return;if(playing){playing=false;ui();return}if(progress>=1)pose(0);playEnd=1;playing=true;last=performance.now();ui()};$('#compare').onclick=()=>{playing=false;pose(progress<.4?.8:0)};$('#timeline').oninput=e=>{playing=false;pose(+e.target.value/1000)};$('#plan').onclick=()=>{planView=!planView;$('#plan').setAttribute('aria-pressed',String(planView));frameView()};$('#pressure').onclick=()=>{showPressure=!showPressure;visible()};$('#details').onclick=()=>{$('#panel').classList.toggle('closed');dirty=true};$('#reset').onclick=()=>{playing=false;showPressure=true;legacy=false;setMode('exterior');pose(0);frameView()};$('#retry').onclick=()=>location.reload();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));if(mobile)$('#panel').classList.add('closed');
Promise.all([fetch('arrangement.json').then(x=>{if(!x.ok)throw Error('Missing arrangement report');return x.json()}),new Promise((res,rej)=>new T.GLTFLoader().load('ATLAS_D_R9.glb',res,e=>{if(e.total)$('#loading').textContent='Loading model · '+Math.round(e.loaded/e.total*100)+'%'},rej))]).then(([rep,gltf])=>{
 report=rep;model=gltf.scene;vessel=model.getObjectByName('Vessel');const clip=gltf.animations[0];if(!vessel||!clip)throw Error('Missing model or animation');for(const tr of clip.tracks){const i=tr.name.lastIndexOf('.'),n=tr.name.slice(0,i),property=tr.name.slice(i+1),object=model.getObjectByName(n);if(!object)throw Error('Unbound target '+n);bindings.push({object,property,interpolant:tr.createInterpolant()})}model.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();o.userData.base={opacity:o.material.opacity,transparent:o.material.transparent,depthWrite:o.material.depthWrite,color:o.material.color.clone()};o.userData.group=group(o);meshes.push(o)});scene.add(model);ready=true;visible();panel();pose(0);frameView();renderer.render(scene,camera);document.body.classList.add('ready');window.ATLAS_R9={ready:true,model,vessel,scene,renderer,camera,controls,report,setMode,pose,frameView,calc,get legacy(){return legacy},get mode(){return mode},get progress(){return progress},get playing(){return playing},inspect(){return{progress,mode,depth:-vessel.position.y,roomCount:report.rooms.length,roomFit:report.geometry_checks.rooms_fit_analytic_planning_radius,tenderFit:report.tender_checks.every(x=>x.sampled_tender_vertices_fit_cylindrical_bore),carrierFit:report.recovery_hardware_checks.every(x=>x.fits_candidate_bore),poolGap:report.pool_revision.vertical_envelope_clearance_m,engineeringValidated:false,mainScale:vessel.scale.toArray()}}};
 }).catch(fail);
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.25);last=now;if(document.hidden)return;if(playing){pose(Math.min(playEnd,progress+dt/48));if(progress>=playEnd){playing=false;ui()}}controls.update();if(dirty||playing){renderer.render(scene,camera);labelsFrame();dirty=false}}requestAnimationFrame(frame);
}catch(e){fail(e)}function fail(e){console.error(e);$('#loading').textContent='Model could not start: '+String(e.message||e);$('#retry').hidden=false;window.ATLAS_R9={ready:false,error:String(e)}}})();
