/* ATLAS D v2: continuous rigid-body motion. Not a physical diving simulator. */
(()=>{'use strict';
const T=window.ATLASRuntime,$=s=>document.querySelector(s),V=(x,y,z)=>new T.Vector3(x,y,z);
try {
let ready=false,p=0,playing=false,direction=1,dry=false,xray=false,spin=false,model,vessel,fleet,clip,bindings=[],redraw=true,view='hero',last=performance.now(),previousDepth=0;
const began=performance.now(),mobile=innerWidth<650,meshes=[],original=new Map();
const smooth=(a,b,x)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
const renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.4:1.55));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
const scene=new T.Scene();scene.background=new T.Color('#b7d0d5');scene.fog=new T.Fog('#b7d0d5',240,900);
const camera=new T.PerspectiveCamera(34,1,.1,2400),controls=new T.OrbitControls(camera,$('#scene'));
controls.enableDamping=true;controls.dampingFactor=.085;controls.minDistance=3;controls.maxDistance=520;controls.maxPolarAngle=Math.PI*.98;
controls.addEventListener('change',()=>{redraw=true});controls.addEventListener('start',()=>{spin=false;$('#orbit').setAttribute('aria-pressed','false')});
const pm=new T.PMREMGenerator(renderer),room=new T.RoomEnvironment();scene.environment=pm.fromScene(room,.045).texture;room.dispose();pm.dispose();scene.environmentIntensity=.94;
const hemi=new T.HemisphereLight(0xe4f4ff,0x263e4b,1.05);scene.add(hemi);
const key=new T.DirectionalLight(0xffefdb,3);key.position.set(-38,75,65);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-62,right:62,top:45,bottom:-45,near:1,far:250});key.shadow.bias=-.0002;key.shadow.normalBias=.045;scene.add(key);scene.add(key.target);
const fill=new T.DirectionalLight(0xb8ddee,1.4);fill.position.set(30,23,-60);scene.add(fill);
const pixels=new Uint8Array(128*128*4);for(let y=0;y<128;y++)for(let x=0;x<128;x++){let i=(y*128+x)*4;pixels[i]=128+14*Math.sin(x*.23+y*.057);pixels[i+1]=128+12*Math.cos(y*.27-x*.12);pixels[i+2]=248;pixels[i+3]=255}
const waterNormal=new T.DataTexture(pixels,128,128);waterNormal.wrapS=waterNormal.wrapT=T.RepeatWrapping;waterNormal.repeat.set(210,210);waterNormal.needsUpdate=true;
const water=new T.Mesh(new T.PlaneGeometry(2400,2400),new T.MeshStandardMaterial({color:0x356a79,roughness:.25,metalness:.25,transparent:true,opacity:.69,depthWrite:false,side:T.DoubleSide,normalMap:waterNormal,normalScale:new T.Vector2(.20,.20)}));water.name='Ocean_surface_fixed_y_0';water.rotation.x=-Math.PI/2;water.position.y=.012;water.receiveShadow=true;scene.add(water);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();redraw=true}addEventListener('resize',resize);resize();
function fit(center,size,dir){const target=V(...center),d=V(...dir).normalize(),right=V(0,1,0).cross(d).normalize(),up=d.clone().cross(right).normalize();const tan=Math.tan(camera.fov*Math.PI/360);let distance=0;for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1]){let c=V(x*size[0]/2,y*size[1]/2,z*size[2]/2);distance=Math.max(distance,Math.abs(c.dot(right))/(tan*camera.aspect)+c.dot(d),Math.abs(c.dot(up))/tan+c.dot(d))}camera.position.copy(target).addScaledVector(d,distance*1.15);controls.target.copy(target);controls.update();redraw=true}
function setView(name='hero'){view=name;const d=ready?vessel.position.y:0;const presets={hero:[[0,7+d,0],[87,23,23],mobile?[1.9,.32,1.45]:[.66,.26,1.4]],profile:[[0,7+d,0],[88,25,19],[0,.07,1]],stern:[[-27,8+d,0],[31,15,17],[-1,.65,.9]],mast:[[-3,17+d,0],[20,8,10],[.2,.75,1.4]]};fit(...(presets[name]||presets.hero));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)))}
function applyXray(){for(const m of meshes){let o=original.get(m),inside=m.name.startsWith('I_');m.visible=inside?xray:true;m.material.opacity=o.opacity;m.material.transparent=o.transparent;m.material.depthWrite=o.depthWrite;if(xray&&!inside&&!m.name.startsWith('S_Fleet')){m.material.opacity=.09;m.material.transparent=true;m.material.depthWrite=false}if(inside&&m.name.startsWith('I_Pressure')){m.material.opacity=m.material.name==='pressure'?.16:.75;m.material.transparent=true;m.material.depthWrite=false}m.material.needsUpdate=true}$('#xray').setAttribute('aria-pressed',String(xray));$('#legend').style.display=xray?'block':'none';redraw=true}
const stages=[
 ['Clear the exterior','Tenders move clear and remain on the surface. The vessel has not begun descending.'],
 ['Stow exposed equipment','The radar mast and sectional guardrails fold onto their supports; pool ladders retract. The hardtop stays fixed.'],
 ['Close the water features','Rigid linked slats unroll from visible cassettes to cover the pool and spa. No decks collapse.'],
 ['Prepare for submergence','The access hatch closes, vent gates shift and foreplanes unfold. The vent-gate sequence is schematic.'],
 ['Controlled submergence','The complete vessel moves down through a fixed waterline. The hull and deck geometry remain unchanged.']
];
function ui(){const ix=p<.16?0:p<.35?1:p<.54?2:p<.70?3:4;$('#stage').textContent=p===0?'Surface configuration':p>=1?'Submerged · same vessel':stages[ix][0];$('#detail').textContent=p===0?'Same hull. Same decks. Follow each mechanism before the vessel descends.':stages[ix][1];$('#timeline').value=Math.round(p*1000);$('#depth').innerHTML=(-vessel.position.y).toFixed(1)+' <span class="depthunit">M<br>MODEL DESCENT</span>';$('#play').textContent=playing?'Pause':p>=1?'Replay dive':p===0?'Start dive':'Continue dive';$('#reverse').textContent=playing&&direction<0?'Surfacing…':'Surface';document.querySelectorAll('[data-step]').forEach((b,i)=>{b.classList.toggle('current',i===ix&&p>0);b.classList.toggle('done',i<ix)});}
function setPose(value,follow=true){if(!ready)return;p=Math.max(0,Math.min(1,value));const time=p*clip.duration;for(const b of bindings){const val=b.interpolant.evaluate(time);b.object[b.property].fromArray(val)}const delta=vessel.position.y-previousDepth;if(follow){camera.position.y+=delta;controls.target.y+=delta}previousDepth=vessel.position.y;key.target.position.y=vessel.position.y;key.position.y=75+vessel.position.y;
const below=smooth(.73,.97,p);scene.background.lerpColors(new T.Color('#b7d0d5'),new T.Color('#0c2e40'),below);scene.fog.color.copy(scene.background);scene.environmentIntensity=.94+below*.25;key.color.lerpColors(new T.Color(0xffefdb),new T.Color(0xafd7f0),below);hemi.intensity=1.05+below*.16;fill.intensity=1.4+below*.2;document.body.classList.toggle('underwater',below>.5);renderer.shadowMap.needsUpdate=true;model.updateMatrixWorld(true);controls.update();ui();redraw=true}
function play(dir=1){if(!ready)return;direction=dir;if(dir>0&&p>=1)setPose(0);if(dir<0&&p<=0)return;playing=true;last=performance.now();ui();redraw=true}
$('#play').onclick=()=>{if(playing){playing=false;ui()}else play(1)};$('#reverse').onclick=()=>play(-1);$('#reset').onclick=()=>{playing=false;setPose(0);setView('hero')};$('#timeline').oninput=e=>{playing=false;setPose(Number(e.target.value)/1000)};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{playing=false;setPose(Number(b.dataset.step))});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#dry').onclick=()=>{dry=!dry;water.visible=!dry;$('#dry').setAttribute('aria-pressed',String(dry));redraw=true};$('#xray').onclick=()=>{xray=!xray;applyXray()};$('#orbit').onclick=()=>{spin=!spin;$('#orbit').setAttribute('aria-pressed',String(spin));redraw=true};
addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();$('#play').click()}});
setView();
function fail(e){console.error(e);$('#loadtext').textContent='The model could not load: '+String(e.message||e);$('#retry').hidden=false;window.ATLAS_D={ready:false,error:String(e)}}
function loaded(gltf){try{model=gltf.scene;model.name='ATLAS_D_Continuous';vessel=model.getObjectByName('Vessel');fleet=model.getObjectByName('Surface_tenders');clip=gltf.animations[0];if(!vessel||!fleet||!clip)throw new Error('Required rig or animation is missing');
model.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();if(o.material.name==='railglass'){o.material.side=T.DoubleSide;o.material.depthWrite=false}if(['warm','light'].includes(o.material.name))o.material.emissiveIntensity=1.1;original.set(o,{opacity:o.material.opacity,transparent:o.material.transparent,depthWrite:o.material.depthWrite});meshes.push(o);o.castShadow=!o.material.transparent;o.receiveShadow=true});
bindings=clip.tracks.map(track=>{const dot=track.name.lastIndexOf('.'),name=track.name.slice(0,dot),property=track.name.slice(dot+1),object=model.getObjectByName(name);if(!object||!['position','quaternion'].includes(property))throw new Error('Unexpected animation track: '+track.name);return{object,property,interpolant:track.createInterpolant()}});
scene.add(model);ready=true;applyXray();setPose(0,false);setView('hero');renderer.render(scene,camera);$('#progress').style.width='100%';document.body.classList.add('ready');
window.ATLAS_D={ready:true,revision:2,model,vessel,fleet,scene,renderer,camera,controls,clip,water,setView,seek:value=>{playing=false;setPose(value)},play,pause:()=>{playing=false;ui()},setXray:value=>{xray=Boolean(value);applyXray()},get state(){return p===0?'surface':p>=1?'submerged':'transition'},get progress(){return p},get transitioning(){return playing},get xray(){return xray},get depth(){return -vessel.position.y},get bindingCount(){return bindings.length},firstFrameMs:Math.round(performance.now()-began),diagnostics(){return{progress:p,depth:-vessel.position.y,hullCount:meshes.filter(m=>m.name.startsWith('S_Hull')).length,alternateEnvelopeNodes:meshes.filter(m=>m.name.startsWith('D_')).length,hullOpaque:meshes.filter(m=>m.name.startsWith('S_Hull')&&['pearl','graphite','white'].includes(m.material.name)).every(m=>m.visible&&m.material.opacity===1),animatedScaleTracks:clip.tracks.filter(t=>t.name.endsWith('.scale')).length,waterY:water.position.y,tenderY:fleet.getWorldPosition(V(0,0,0)).y,deckAndHullLocalScaleFixed:meshes.filter(m=>/^S_(Hull|Architecture|Deck)__/.test(m.name)).every(m=>m.scale.equals(V(1,1,1)))}}};
}catch(e){fail(e)}}
const loader=new T.GLTFLoader();if(window.ATLAS_EMBEDDED_GLB){try{const str=atob(window.ATLAS_EMBEDDED_GLB),bytes=new Uint8Array(str.length);for(let i=0;i<str.length;i++)bytes[i]=str.charCodeAt(i);loader.parse(bytes.buffer,'',loaded,fail);const url=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'}));$('#download').href=url;$('#download').download='ATLAS_D_Continuous_Dive.glb'}catch(e){fail(e)}}else loader.load('./ATLAS_D_Continuous_Dive.glb',loaded,e=>{if(e.total)$('#progress').style.width=Math.round(e.loaded/e.total*100)+'%'},fail);
function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,Math.min(.1,(now-last)/1000));last=now;if(document.hidden)return;if(ready&&playing){setPose(p+dt/clip.duration*direction);if((direction>0&&p>=1)||(direction<0&&p<=0)){playing=false;ui()}}if(ready&&spin){const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(V(0,1,0),dt*.085);camera.position.copy(controls.target).add(offset);redraw=true}controls.update();if(redraw){renderer.render(scene,camera);redraw=false}}requestAnimationFrame(frame);
} catch(e) { console.error(e); $('#loadtext').textContent='3D graphics are unavailable in this browser. Open this file in a WebGL-capable browser.'; $('#retry').hidden=false; window.ATLAS_D={ready:false,error:String(e)}; }
})();
