/* ATLAS D R5: fixed architecture; rigid exterior fittings. Illustrative motion, not operational control. */
(()=>{'use strict';const T=window.ATLASRuntime,$=s=>document.querySelector(s),V=(...x)=>new T.Vector3(...x),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
let model,vessel,ready=false,bindings=[],meshes=[],p=0,playing=false,end=.62,dir=1,view='hero',dry=false,core=false,bays=false,spin=false,redraw=true,last=performance.now(),depth=0;const mobile=innerWidth<650;
try{
const r=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.35:1.7));r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.02;r.shadowMap.enabled=true;r.shadowMap.autoUpdate=false;r.shadowMap.type=T.PCFSoftShadowMap;
const s=new T.Scene();s.background=new T.Color('#b6cbd0');s.fog=new T.Fog('#b6cbd0',240,1700);const c=new T.PerspectiveCamera(31,1,.15,3000);const controls=new T.OrbitControls(c,$('#scene'));controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=4;controls.maxDistance=380;controls.maxPolarAngle=Math.PI*.95;controls.addEventListener('change',()=>{redraw=true});controls.addEventListener('start',()=>{spin=false;$('#orbit').classList.remove('active')});
// Broad sky/horizon environment, without repeated room lights in every window.
const ew=512,eh=256,data=new Uint8Array(ew*eh*4);for(let y=0;y<eh;y++){const t=y/(eh-1),a=t<.5?[.33+.92*t,.46+.72*t,.56+.52*t]:[.26-.28*(t-.5),.36-.38*(t-.5),.40-.42*(t-.5)];for(let x=0;x<ew;x++){const i=(y*ew+x)*4,sun=Math.exp(-((x/ew-.22)**2/.013+(t-.32)**2/.04))*.19;for(let k=0;k<3;k++)data[i+k]=Math.min(255,255*(a[k]+sun));data[i+3]=255}}const env=new T.DataTexture(data,ew,eh);env.mapping=303;env.colorSpace=T.SRGBColorSpace;env.needsUpdate=true;const pm=new T.PMREMGenerator(r);s.environment=pm.fromEquirectangular(env).texture;pm.dispose();env.dispose();s.environmentIntensity=.82;
s.add(new T.HemisphereLight(0xdfeff5,0x334a50,1.30));const sun=new T.DirectionalLight(0xffecd6,3.2);sun.position.set(-25,65,45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-58,right:58,top:32,bottom:-32,near:1,far:180});sun.shadow.bias=-.0001;sun.shadow.normalBias=.025;s.add(sun);s.add(sun.target);const fill=new T.DirectionalLight(0xc4dfed,.9);fill.position.set(30,18,-65);s.add(fill);
const n=256,pix=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=(y*n+x)*4;pix[i]=128+8*Math.sin(x*.085+y*.053)+3*Math.cos(x*.17-y*.115);pix[i+1]=128+7*Math.cos(y*.12-x*.067)+4*Math.sin(x*.043+y*.019);pix[i+2]=253;pix[i+3]=255}const normal=new T.DataTexture(pix,n,n);normal.wrapS=normal.wrapT=T.RepeatWrapping;normal.repeat.set(110,110);normal.needsUpdate=true;
const water=new T.Mesh(new T.PlaneGeometry(4000,4000),new T.MeshStandardMaterial({color:0x2e6470,roughness:.32,metalness:.27,normalMap:normal,normalScale:new T.Vector2(.055,.055),side:T.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=.01;water.receiveShadow=true;s.add(water);
function resize(){r.setSize(innerWidth,innerHeight,false);c.aspect=innerWidth/innerHeight;c.updateProjectionMatrix();redraw=true}window.addEventListener('resize',()=>{resize();setView(view)});resize();
function fit(center,size,vector){const target=V(...center),d=V(...vector).normalize(),right=V(0,1,0).cross(d).normalize(),up=d.clone().cross(right).normalize();let dist=0;const tan=Math.tan(c.fov*Math.PI/360);for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1]){const q=V(x*size[0]/2,y*size[1]/2,z*size[2]/2);dist=Math.max(dist,Math.abs(q.dot(right))/(tan*c.aspect)+q.dot(d),Math.abs(q.dot(up))/tan+q.dot(d))}c.position.copy(target).addScaledVector(d,dist*(mobile?1.12:1.13));controls.target.copy(target);c.setViewOffset(innerWidth,innerHeight,0,mobile?25:56,innerWidth,innerHeight);c.updateProjectionMatrix();controls.update();redraw=true}
function setView(name='hero'){view=name;const y=ready?vessel.position.y:0;const presets={hero:[[0,5.7+y,0],[85,17,20],mobile?[1.5,.50,1.45]:[.65,.37,1.4]],profile:[[0,6+y,0],[85,17,18],[0,.035,1]],aft:[[-24,6+y,0],[37,14,21],[-1,.70,1.25]],canopy:[[-8,10+y,0],[26,7,13],[-1,.68,1.3]],mast:[[2.6,11.7+y,0],[11,7,9],[.6,.6,1.3]],terraces:[[-21,3.2+y,0],[20,8,23],[-.65,.60,1.4]],core:[[0,1+y,0],[59,11,15],[.35,.32,1.4]]};fit(...(presets[name]||presets.hero));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function notice(title,copy){$('#explain').hidden=false;$('#inspect-title').textContent=title;$('#inspect-copy').textContent=copy}
function style(){for(const o of meshes){const b=o.userData.base;let alpha=b.opacity,visible=true;const sys=o.userData.system;if(sys){visible=core;if(o.parent?.name==='SYS_Pressure'&&o.material.name.startsWith('Pressure boundary'))alpha=.22;}else if(core){alpha=.07;visible=o.userData.group==='EX_Main_hull'||o.userData.group==='EX_Integrated_architecture'}else if(bays&&['EX_Integrated_architecture','EX_Sensor_well'].includes(o.userData.group)){alpha=.13;}o.visible=visible;o.material.opacity=alpha;o.material.transparent=b.transparent||alpha<.999;o.material.depthWrite=b.depthWrite&&alpha>.94;o.material.needsUpdate=true;}water.visible=!dry&&!core;r.shadowMap.needsUpdate=true;redraw=true;$('#core').setAttribute('aria-pressed',String(core));$('#bays').setAttribute('aria-pressed',String(bays));$('#dry').setAttribute('aria-pressed',String(dry))}
function ui(){let text='A single, integrated silhouette',detail='Permanent deckhouses. Stowable exterior fittings.';if(p>0&&p<.14){text='Clear & lower the sensor mast';detail='The compact sensor pack enters its dedicated trunk.'}else if(p<.34&&p>=.14){text='Retract the canopy · extend pool covers';detail='Rigid parts travel into or out of their modeled storage bays.'}else if(p<.50&&p>=.34){text='Fold terraces into the hull recesses';detail='Exterior panels close; the occupied pressure core does not move.'}else if(p<.74&&p>=.50){text='Fittings stowed · held above water';detail='Inspect the conversion before the descent begins.'}else if(p>=.74){text='Illustrative submerged configuration';detail='Same vessel, same fixed core. No demonstrated safe operating depth.'}$('#stage').textContent=text;$('#detail').textContent=detail;$('#mode').textContent=p===0?'SURFACE':p<.74?'STOWING':'SUBMERGED';$('#pct').textContent=String(Math.round(p*100)).padStart(2,'0')+'%';$('#timeline').value=Math.round(p*1000);$('#convert').innerHTML=playing?'Pause':'Convert fittings <span>→</span>';$('#phase').textContent=p<.74?'FITTINGS → STOWED → DESCENT':'ILLUSTRATIVE DEPTH '+depth.toFixed(1)+' m';}
function pose(value){if(!ready)return;p=clamp(value,0,1);const prev=vessel.position.y;for(const b of bindings)b.object[b.property].fromArray(b.interpolant.evaluate(p*36));model.updateMatrixWorld(true);const delta=vessel.position.y-prev;c.position.y+=delta;controls.target.y+=delta;depth=-vessel.position.y;sun.position.y=65+vessel.position.y;sun.target.position.y=vessel.position.y;const underwater=smooth(1.5,13,depth);s.background.lerpColors(new T.Color('#b6cbd0'),new T.Color('#082a3a'),underwater);s.fog.color.copy(s.background);document.body.classList.toggle('underwater',underwater>.5);r.shadowMap.needsUpdate=true;ui();redraw=true;}
function play(target){if(playing){playing=false;ui();return}if(!ready)return;if(p>=target-.001)pose(0);end=target;dir=1;playing=true;last=performance.now();ui()}
$('#convert').onclick=()=>play(.62);$('#dive').onclick=()=>play(1);$('#compare').onclick=()=>{playing=false;pose(p<.31?.62:0)};$('#reset').onclick=()=>{playing=false;pose(0);core=false;bays=false;dry=false;style();setView('hero');$('#explain').hidden=true};$('#timeline').oninput=e=>{playing=false;pose(+e.target.value/1000)};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#orbit').onclick=()=>{spin=!spin;$('#orbit').classList.toggle('active',spin)};$('#dry').onclick=()=>{dry=!dry;style()};$('#core').onclick=()=>{core=!core;bays=false;style();setView(core?'core':'hero');if(core)notice('Fixed pressure enclosure','The cylindrical core is carried forward from the prior arrangement study. No folding rooms, shell thickness validation or safe-depth rating. The outer yacht structures are not credited as pressure-resistant accommodation.');else $('#explain').hidden=true};$('#bays').onclick=()=>{bays=!bays;core=false;style();setView('canopy');if(bays)notice('Visible stowage paths','The canopy slides between the fixed crown and soffit. The mast has a separate well; four pool-cover leaves share an aft cassette. The ghosted shell is an inspection overlay—not an animated disappearance.');else $('#explain').hidden=true};$('#close-note').onclick=()=>$('#explain').hidden=true;$('#retry').onclick=()=>location.reload();
setView();new T.GLTFLoader().load('./ATLAS_D_R5.glb',gltf=>{model=gltf.scene;vessel=model.getObjectByName('Vessel');if(!vessel)throw Error('Vessel root missing');const clip=gltf.animations[0];if(!clip)throw Error('Rigid motion clip missing');for(const tr of clip.tracks){const dot=tr.name.lastIndexOf('.'),name=tr.name.slice(0,dot),prop=tr.name.slice(dot+1),object=model.getObjectByName(name);if(!object)throw Error('Unbound track '+name);bindings.push({object,property:prop,interpolant:tr.createInterpolant()});}model.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();o.castShadow=!o.material.transparent;o.receiveShadow=true;let parent=o;while(parent.parent&&parent.parent!==vessel&&parent.parent!==model)parent=parent.parent;let n=o,sys=false;while(n){if(n.name.startsWith('SYS_'))sys=true;n=n.parent;}o.userData={base:{opacity:o.material.opacity,transparent:o.material.transparent,depthWrite:o.material.depthWrite},system:sys,group:parent.name};meshes.push(o)});s.add(model);ready=true;style();pose(0);setView();r.render(s,c);document.body.classList.add('ready');window.ATLAS_R5={ready:true,model,vessel,scene:s,renderer:r,camera:c,controls,pose,setView,play,report:null,get progress(){return p},get playing(){return playing},get depth(){return depth},inspect(){return{progress:p,depth,canopy:model.getObjectByName('MOV_Aft_canopy').position.toArray(),mast:model.getObjectByName('MOV_Sensor_mast').position.toArray(),terrace:model.getObjectByName('MOV_Terrace_1').quaternion.toArray(),coreFixed:true,renderCalls:r.info.render.calls}}};fetch('./model_report.json').then(x=>x.json()).then(x=>window.ATLAS_R5.report=x);},ev=>{if(ev.total){$('#progress').style.width=100*ev.loaded/ev.total+'%';$('#loadcopy').textContent='Loading model · '+Math.round(100*ev.loaded/ev.total)+'%'}},fail);
function frame(now){requestAnimationFrame(frame);const elapsed=(now-last)/1000,dt=Math.min(elapsed,.05);last=now;if(document.hidden)return;if(playing){pose(Math.min(end,p+elapsed/36));if(p>=end){playing=false;ui()}}if(spin&&ready){let d=c.position.clone().sub(controls.target);d.applyAxisAngle(V(0,1,0),dt*.09);c.position.copy(controls.target).add(d);redraw=true}controls.update();if(redraw||playing||spin){r.render(s,c);redraw=false}}requestAnimationFrame(frame);
}catch(e){fail(e)}
function fail(e){console.error(e);$('#loadcopy').textContent='The model could not start. Please retry.';$('#retry').hidden=false;window.ATLAS_R5={ready:false,error:String(e)}}
})();
