/* ATLAS D / 03. Calculated hydrostatic pressure; schematic kinematics and system logic.
   No dynamic buoyancy solution, engineering rating or operational control system. */
(()=>{'use strict';
const T=window.ATLASRuntime,$=s=>document.querySelector(s),V=(...a)=>new T.Vector3(...a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const smooth=(a,b,p)=>{const t=clamp((p-a)/(b-a),0,1);return t*t*(3-2*t)};
const RHO=1025,GRAV=9.80665,CABIN=1.01325;
try{
let stopAt=null;let ready=false,model,vessel,fleet,clip,bindings=[],p=0,playing=false,direction=1,xray=false,dry=false,flow=false,spin=false,fault=false,trim=false,recovery=null,system='all',view='hero',previousDepth=0,redraw=true,last=performance.now(),inspector=false;
const mobile=innerWidth<650,meshes=[],base=new Map(),began=performance.now();
const renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.25:1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;
renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
const scene=new T.Scene();scene.background=new T.Color('#b7d0d5');scene.fog=new T.Fog('#b7d0d5',270,1200);
const camera=new T.PerspectiveCamera(34,1,.1,2400),controls=new T.OrbitControls(camera,$('#scene'));controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=3;controls.maxDistance=540;controls.maxPolarAngle=Math.PI*.97;
controls.addEventListener('change',()=>{redraw=true});controls.addEventListener('start',()=>{spin=false;$('#orbit').setAttribute('aria-pressed','false')});
const pm=new T.PMREMGenerator(renderer),room=new T.RoomEnvironment();scene.environment=pm.fromScene(room,.055).texture;room.dispose();pm.dispose();scene.environmentIntensity=.92;
const hemi=new T.HemisphereLight(0xe6f4ff,0x304950,1.15);scene.add(hemi);const key=new T.DirectionalLight(0xfff1dd,3.0);key.position.set(-38,75,65);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-63,right:63,top:48,bottom:-48,near:1,far:260});key.shadow.normalBias=.04;key.shadow.bias=-.00016;scene.add(key);scene.add(key.target);
const fill=new T.DirectionalLight(0xc3e0ea,1.5);fill.position.set(25,32,-60);scene.add(fill);
const pix=new Uint8Array(128*128*4);for(let y=0;y<128;y++)for(let x=0;x<128;x++){let i=(y*128+x)*4;pix[i]=128+13*Math.sin(x*.23+y*.057);pix[i+1]=128+13*Math.cos(y*.27-x*.12);pix[i+2]=248;pix[i+3]=255}
const norm=new T.DataTexture(pix,128,128);norm.wrapS=norm.wrapT=T.RepeatWrapping;norm.repeat.set(210,210);norm.needsUpdate=true;
const water=new T.Mesh(new T.PlaneGeometry(2400,2400),new T.MeshStandardMaterial({color:0x326b79,roughness:.26,metalness:.23,transparent:true,opacity:.71,depthWrite:false,side:T.DoubleSide,normalMap:norm,normalScale:new T.Vector2(.19,.19)}));water.rotation.x=-Math.PI/2;water.position.y=.012;water.name='Fixed ocean surface';water.receiveShadow=true;scene.add(water);
const particles=new T.Group();scene.add(particles);const dots=[];const dotgeo=new T.BoxGeometry(.07,.25,.07),dotmat=new T.MeshBasicMaterial({color:0x79ecdf,transparent:true,opacity:.85,depthWrite:false});
for(const side of [-1,1])for(const x of [-18,-6,6,18])for(let k=0;k<4;k++){let d=new T.Mesh(dotgeo,dotmat);d.userData={side,x,k};particles.add(d);dots.push(d)}particles.visible=false;
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();redraw=true}addEventListener('resize',resize);resize();
function fit(center,size,dir){const target=V(...center),d=V(...dir).normalize(),right=V(0,1,0).cross(d).normalize(),up=d.clone().cross(right).normalize();const tan=Math.tan(camera.fov*Math.PI/360);let dist=0;for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1]){const c=V(x*size[0]/2,y*size[1]/2,z*size[2]/2);dist=Math.max(dist,Math.abs(c.dot(right))/(tan*camera.aspect)+c.dot(d),Math.abs(c.dot(up))/tan+c.dot(d))}camera.position.copy(target).addScaledVector(d,dist*(mobile?1.17:1.16));controls.target.copy(target);camera.setViewOffset(innerWidth,innerHeight,!mobile&&inspector?-125:0,mobile?20:35,innerWidth,innerHeight);camera.updateProjectionMatrix();controls.update();redraw=true}
function setView(name='hero'){view=name;const y=ready?vessel.position.y:0;const presets={hero:[[0,7+y,0],[87,24,25],mobile?[1.8,.38,1.6]:[.7,.32,1.4]],profile:[[0,8+y,0],[87,25,24],[0,.12,1]],mechanism:[[0,11+y,0],[42,16,14],[.2,.6,1.5]],stern:[[-31,4.5+y,0],[19,11,24],[-.9,.7,1.4]],seals:[[-18,5.9+y,0],[8,5,8],[-.6,.7,1.2]],pressure:[[0,.8+y,0],[61,10,16],[.35,.33,1.4]],ballast:[[0,1+y,0],[64,11,17],[.45,.7,1.5]],wet:[[-2,10+y,0],[50,14,17],[.5,.5,1.4]],energy:[[0,.2+y,0],[51,11,14],[.4,.6,1.4]],recovery:[[0,-2.3+y,0],[53,7,16],[.5,-.1,1.4]]};fit(...(presets[name]||presets.hero));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)))}
function ancestry(o){let n=o;while(n){if(n.name.startsWith('SYS_'))return n.name;n=n.parent}return 'EXTERIOR'}
const subset={all:null,pressure:['SYS_Pressure','SYS_Closures'],ballast:['SYS_Ballast','SYS_Trim'],wet:['SYS_WetSpaces','SYS_FloodVents'],energy:['SYS_Energy','SYS_LifeSupport','SYS_Pressure','SYS_Isolation'],closures:['SYS_Closures','SYS_Isolation','SYS_FloodVents'],recovery:['SYS_Recovery','SYS_Ballast']};
const descriptions={all:['What stays dry?','The lower pressure capsule is the proposed dry enclosure. Upper rooms have been replaced by open leisure canopies. Only unoccupied exterior hardware folds; the proposed dry core stays fixed.'],pressure:['A fixed pressure boundary','A cylindrical midbody with hemispherical ends, indicative frames, seated hatches and small viewing ports. Thickness, reinforcements and openings still need structural design.'],ballast:['Buoyancy is not a hull swap','Main tanks admit seawater while air vents from their tops. A separate trim circuit transfers water fore and aft. Mass, reserve buoyancy and stability have not been solved.'],wet:['Wet outside. Dry inside.','These cyan pavilions fill as the waterline passes through them. They must be unoccupied and flood-compatible. The large yacht glazing is not credited as a pressure window.'],energy:['Isolate the sea from the cabin','Air-service isolation valves close before flooding. Submerged operation is represented as electric-only. Battery, oxygen, scrubber and heat-rejection capacities are unassigned.'],closures:['Two very different closures','Access hatches and service valves belong to the proposed dry boundary. Pool covers are debris fairings, not pressure doors. Exterior flood equalizers OPEN rather than seal shut.'],recovery:['An independent way back','Releasable weights and an emergency air bank are represented. The recovery animation shows intent, not a verified positive-buoyancy or survival capability.']};
function visibility(){for(const m of meshes){const b=base.get(m),gr=m.userData.system,sys=gr!=='EXTERIOR';let visible=true,alpha=b.opacity;
 if(sys){const hiddenCore=['SYS_Pressure','SYS_Habitation','SYS_Energy','SYS_LifeSupport','SYS_Ballast','SYS_Trim','SYS_WetSpaces'].includes(gr);visible=xray?(system==='all'||(subset[system]||[]).includes(gr)):!hiddenCore;
  if(xray&&gr==='SYS_Pressure'){alpha=m.name.startsWith('Pressure_capsule')?(system==='pressure'?.58:.14):.90}
 }else if(xray){alpha=m.name.startsWith('S_Fleet')?.32:.075;}
 m.visible=visible;m.material.opacity=alpha;m.material.transparent=b.transparent||alpha<.999;m.material.depthWrite=b.depthWrite&&alpha>.93;m.material.needsUpdate=true;
 }water.visible=!dry&&!xray;particles.visible=flow;$('#xray').setAttribute('aria-pressed',String(xray));$('#dry').setAttribute('aria-pressed',String(dry));redraw=true}
function inspectorSet(v){inspector=Boolean(v);document.body.classList.toggle('inspect',inspector);$('#inspect-button').setAttribute('aria-pressed',String(inspector));setView(view)}
function setXray(value){xray=Boolean(value);if(!mobile)inspectorSet(xray);visibility();if(xray)setView(system==='all'?'pressure':system==='closures'?'seals':system);else setView('hero')}
function setSystem(value){system=descriptions[value]?value:'all';$('#system').value=system;const [title,copy]=descriptions[system];$('#inspect-title').textContent=title;$('#inspect-copy').textContent=copy;if(!xray)xray=true;visibility();setView(system==='all'?'pressure':system==='closures'?'seals':system)}
function pressureAtDepth(depth){return RHO*GRAV*Math.max(0,depth)/100000}
function condition(id,text,ok){$('#state-'+id).textContent=text;$('#check-'+id).classList.toggle('complete',ok)}
const stages=[['Clear the exterior','Surface-only spaces are vacated; tenders move clear and remain afloat.'],['Transform the exterior','Daybeds and radar fold; constant-length scissor supports lower the two canopy roofs. Side terraces fold in; the aft fairing closes.'],['Isolate the dry boundary','Candidate access hatches seat and lock. Air-service isolation valves close.'],['Vent and flood','Exterior equalizers and main-ballast top vents open; seawater replaces air.'],['Descend as one vessel','The pressure capsule stays dry in the diagram. Upper pavilions flood at the fixed waterline.'],['Submerged arrangement','Electric-only mode is represented. A 40 m datum descent is shown—not a certified operating depth.']];
function stageIndex(){return p<.13?0:p<.36?1:p<.48?2:p<.64?3:p<.95?4:5}
function ui(){if(!ready)return;const d=Math.max(0,-vessel.position.y),dp=pressureAtDepth(d),idx=stageIndex();$('#depth').innerHTML=d.toFixed(1)+' <small>m</small>';$('#pressure').innerHTML=dp.toFixed(2)+' <small>bar</small>';$('#roofdrop').innerHTML=(5.16*smooth(.28,.54,p)).toFixed(2)+' <small>m</small>';$('#keel').textContent=pressureAtDepth(d+3).toFixed(2)+' bar ΔP';
 $('#timeline').value=Math.round(p*1000);const seconds=Math.floor(p*42);$('#clock').textContent='0:'+String(seconds).padStart(2,'0');$('#mode-badge').textContent=recovery?(recovery.kind==='normal'?'ASCENT':'RECOVERY'):d>.1?'SUBMERGED':p===0?'SURFACE':'PREPARE';
 $('#stage').textContent=recovery?(recovery.done?'Surface · closures retained':recovery.kind==='normal'?'Close ballast vents · blow · ascend':'Recovery concept demonstration'):fault&&p>=.46?'Dive inhibited · hatch fault':p===0?'Surface configuration':stages[idx][0];$('#detail').textContent=recovery?(recovery.kind==='normal'?'Main-ballast vents close before the blow illustration; exterior equalizers stay open. Ascent is prescribed, not dynamically solved.':'Illustrative release and ascent only. Recovery mass and buoyancy margins are NOT verified.'):fault&&p>=.46?'A simulated obstruction blocks further dive progress. Clear the fault to continue.':stages[idx][1];
 $('#play').textContent=playing?'Pause':p>=1?'Replay dive':p>=.60?'Dive':'Full sequence';$('#transform').textContent=playing&&stopAt!==null?'Transforming…':'Transform only';if(!playing&&Math.abs(p-.62)<.003){$('#stage').textContent='Dive-ready silhouette · held above water';$('#detail').textContent='Compare the lower roofline, folded terraces and closed aft deck. The same hull and pressure core are still here.';}$('#reverse').textContent=playing&&direction<0?'Surfacing…':'Surface';condition('hatch',fault?'FAULT':p>=.46?'MODELED SHUT':'OPEN / MOVING',!fault&&p>=.46);condition('air',p>=.46?'MODELED SHUT':'OPEN / MOVING',p>=.46);condition('vent',p>=.61?'OPEN':p>.47?'OPENING':'CLOSED',p>=.61);condition('ballast',Math.round((recovery?.kind==='normal'?recovery.fill:smooth(.52,.70,p))*100)+'%',p>=.70);
 document.querySelectorAll('[data-step]').forEach((b,i)=>{b.classList.toggle('current',idx===i&&p>0);b.classList.toggle('done',i<idx)});
}
function fills(){const f=recovery?.kind==='normal'?recovery.fill:smooth(.52,.70,p),depth=-vessel.position.y;for(const m of meshes){const b=base.get(m);if(m.name.startsWith('MBT_water')){m.scale.y=Math.max(.001,f);m.position.y=-1.54+1.54*f;}if(m.name.startsWith('Wet_pavilion')){const h=b.size.y;const fraction=clamp((depth-(b.position.y-h/2))/h,0,1);m.scale.y=Math.max(.001,fraction);m.position.y=b.position.y-h/2+h*fraction/2;m.visible=xray&&(system==='all'||system==='wet')&&fraction>.002;}
 if(m.name.startsWith('Trim_water')){const amount=trim?(m.name.includes('forward')?.68:.32):.5;m.scale.y=amount;m.position.y=-.25+.45*amount;}
 }}
function moveCameraWithVessel(){const delta=vessel.position.y-previousDepth;camera.position.y+=delta;controls.target.y+=delta;previousDepth=vessel.position.y;key.target.position.y=vessel.position.y;key.position.y=75+vessel.position.y;const below=clamp((-vessel.position.y-2)/24,0,1);scene.background.lerpColors(new T.Color('#b7d0d5'),new T.Color('#0b2a3b'),below);scene.fog.color.copy(scene.background);key.color.lerpColors(new T.Color(0xfff1dd),new T.Color(0xb1ddee),below);scene.environmentIntensity=.92+below*.15;document.body.classList.toggle('underwater',below>.5);renderer.shadowMap.needsUpdate=!playing;}
function pose(value,follow=true){if(!ready)return;let next=clamp(value,0,1);if(fault&&next>p&&next>.46){next=Math.max(.46,p);playing=false;$('#notice').hidden=false;$('#notice').textContent='DIVE INHIBITED: simulated access-hatch obstruction. No descent is permitted by this demonstration.';}
 p=next;for(const b of bindings){const val=b.interpolant.evaluate(p*clip.duration);b.object[b.property].fromArray(val)}if(fault&&-vessel.position.y<.01){const h=model.getObjectByName('Pressure_hatch_hinge_-18');if(h)h.quaternion.set(Math.sin(-.5),0,0,Math.cos(-.5));}
 if(follow)moveCameraWithVessel();else previousDepth=vessel.position.y;fills();model.updateMatrixWorld(true);controls.update();ui();redraw=true;
}
function play(dir=1){if(!ready||recovery)return;direction=dir;if(dir>0&&p>=1)pose(0);if(dir<0&&p<=0)return;playing=true;last=performance.now();ui()}
function reset(){stopAt=null;playing=false;recovery=null;fault=false;trim=false;$('#fault').setAttribute('aria-pressed','false');$('#trim').setAttribute('aria-pressed','false');$('#notice').hidden=true;for(const m of meshes)if(m.name.startsWith('Emergency_drop_weight'))m.position.copy(base.get(m).position);pose(0);setView('hero');$('#demo-copy').textContent='Demonstrations are teaching controls, not safety-rated software.';}
function setFault(value){fault=Boolean(value);playing=false;$('#fault').setAttribute('aria-pressed',String(fault));$('#notice').hidden=!fault;$('#notice').textContent=-vessel.position.y>.1?'Simulated hatch-status disagreement. Animation paused; the model does not open a pressure hatch underwater.':'Hatch obstruction enabled. The sequence will stop before venting and descent.';if(!fault)$('#demo-copy').textContent='Fault cleared in the software demonstration.';pose(p);}
function surface(){if(!ready)return;if(-vessel.position.y<.1){if(recovery)reset();else play(-1);return;}playing=false;recovery={kind:'normal',started:performance.now(),startY:vessel.position.y,initialFill:smooth(.52,.70,p),fill:smooth(.52,.70,p),done:false};$('#notice').hidden=false;$('#notice').textContent='NORMAL ASCENT STUDY: main-ballast top vents close, then an air-blow illustration displaces water. Exterior pavilions drain as they emerge. Gas inventory and buoyancy are unverified.';ui()}
function emergency(){if(!ready||recovery)return;if(-vessel.position.y<8){$('#notice').hidden=false;$('#notice').textContent='Advance into the submerged scene first. Recovery capacity is unverified; this is a visual demonstration only.';return}playing=false;recovery={started:performance.now(),startY:vessel.position.y,done:false};$('#notice').hidden=false;$('#notice').textContent='RECOVERY CONCEPT: weights release and the vessel rises on a prescribed path. Positive-buoyancy margin is not calculated. Pressure hatches stay closed.';ui()}
$('#play').onclick=()=>{stopAt=null;if(recovery){reset();return}if(playing){playing=false;ui()}else play(1)};$('#reverse').onclick=()=>surface();$('#reset').onclick=reset;$('#timeline').oninput=e=>{playing=false;recovery=null;pose(Number(e.target.value)/1000)};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{playing=false;recovery=null;pose(Number(b.dataset.step))});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='seals'&&!xray)setXray(true);setView(b.dataset.view)});
$('#system').onchange=e=>setSystem(e.target.value);$('#xray').onclick=()=>setXray(!xray);$('#inspect-button').onclick=()=>inspectorSet(!inspector);$('#close-inspector').onclick=()=>inspectorSet(false);$('#dry').onclick=()=>{dry=!dry;visibility()};$('#flows').onclick=()=>{flow=!flow;particles.visible=flow;$('#flows').setAttribute('aria-pressed',String(flow));redraw=true};$('#orbit').onclick=()=>{spin=!spin;$('#orbit').setAttribute('aria-pressed',String(spin));redraw=true};$('#fault').onclick=()=>setFault(!fault);$('#trim').onclick=()=>{trim=!trim;$('#trim').setAttribute('aria-pressed',String(trim));$('#demo-copy').textContent=trim?'Forward trim-water fraction rises while aft fraction falls by the same amount. Total water is conserved; pitch response is not solved.':'Trim-water distribution returned to equal fractions.';setSystem('ballast');fills();redraw=true};$('#emergency').onclick=emergency;

$('#transform').onclick=()=>{reset();if(xray)setXray(false);setView('profile');stopAt=.62;play(1)};
$('#compare').onclick=()=>{const next=p>.3?0:.62;reset();if(xray)setXray(false);pose(next);setView('profile')};

setView();
function fail(e){console.error(e);$('#loadtext').textContent='The 3D model could not load: '+String(e.message||e);$('#retry').hidden=false;window.ATLAS_D={ready:false,error:String(e)}}
new T.GLTFLoader().load('./ATLAS_D_R4.glb',gltf=>{try{model=gltf.scene;vessel=model.getObjectByName('Vessel');fleet=model.getObjectByName('Surface_tenders');clip=gltf.animations[0];if(!vessel||!fleet||!clip)throw new Error('Articulated vessel is missing');
model.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();if(o.material.name==='railglass'){o.material.side=T.DoubleSide;o.material.depthWrite=false}if(['warm','light'].includes(o.material.name))o.material.emissiveIntensity=1.1;o.userData.system=ancestry(o);o.geometry.computeBoundingBox();base.set(o,{position:o.position.clone(),scale:o.scale.clone(),opacity:o.material.opacity,transparent:o.material.transparent,depthWrite:o.material.depthWrite,size:o.geometry.boundingBox.getSize(V(0,0,0))});meshes.push(o);o.castShadow=!o.material.transparent;o.receiveShadow=true});
bindings=clip.tracks.map(t=>{const dot=t.name.lastIndexOf('.'),name=t.name.slice(0,dot),property=t.name.slice(dot+1),object=model.getObjectByName(name);if(!object||!['position','quaternion'].includes(property))throw new Error('Invalid rigid-motion track '+t.name);return{object,property,interpolant:t.createInterpolant()}});
scene.add(model);ready=true;visibility();pose(0,false);setView('hero');renderer.render(scene,camera);document.body.classList.add('ready');
window.ATLAS_D={ready:true,revision:4,model,vessel,fleet,water,scene,camera,renderer,controls,clip,seek:v=>{playing=false;recovery=null;pose(v)},play,pause:()=>{playing=false;ui()},reset,setView,setXray,setSystem,setFault,emergency,surface,pressureAtDepth,get depth(){return -vessel.position.y},get progress(){return p},get fault(){return fault},get recovery(){return recovery},get transitioning(){return playing},get xray(){return xray},firstFrameMs:Math.round(performance.now()-began),diagnostics(){return{revision:4,progress:p,datumDepth:-vessel.position.y,pressureBar:pressureAtDepth(-vessel.position.y),cabinBar:CABIN,ballastFill:recovery?.kind==='normal'?recovery.fill:smooth(.52,.70,p),mainBallastVentClosed:recovery?.kind==='normal',waterY:water.position.y,tenderY:fleet.position.y,hullCount:meshes.filter(m=>m.name.startsWith('S_Hull')).length,scaleTracks:clip.tracks.filter(t=>t.name.endsWith('.scale')).length,pressureHatchesClosed:p>=.46&&!fault,externalEqualizersOpen:p>=.61,ratedDepth:null,dynamicsSolved:false,rigidBindings:bindings.length}}};
fetch('model_report.json').then(r=>r.json()).then(r=>window.ATLAS_D.report=r).catch(()=>{});
}catch(e){fail(e)}},e=>{if(e.total){$('#progress').style.width=(e.loaded/e.total*100)+'%';$('#loadtext').textContent='Loading articulated model · '+Math.round(e.loaded/e.total*100)+'%'}},fail);
function frame(now){requestAnimationFrame(frame);if(document.hidden){last=now;return}const dt=Math.min(.075,(now-last)/1000);last=now;if(playing){pose(p+direction*dt/42);if(stopAt!==null&&p>=stopAt){pose(stopAt);playing=false;stopAt=null;ui()}if(p>=1||p<=0){playing=false;ui()}}
if(recovery&&!recovery.done){const t=clamp((now-recovery.started)/18000,0,1);if(recovery.kind==='normal'){recovery.fill=recovery.initialFill*(1-.78*smooth(.14,.76,t));for(const m of meshes)if(m.name.startsWith('MBT_top_vent_lift'))m.position.y=5.33-.21*smooth(0,.12,t);}vessel.position.y=recovery.startY*(1-smooth(recovery.kind==='normal'?.26:.16,1,t));for(const m of meshes)if(recovery.kind!=='normal'&&m.name.startsWith('Emergency_drop_weight')){const b=base.get(m);m.position.y=b.position.y-70*smooth(0,1,t)-(vessel.position.y-recovery.startY)}moveCameraWithVessel();fills();model.updateMatrixWorld(true);if(t===1)recovery.done=true;ui();redraw=true}
if(spin&&ready){const d=camera.position.clone().sub(controls.target);d.applyAxisAngle(V(0,1,0),dt*.08);camera.position.copy(controls.target).add(d);redraw=true}
if(flow&&ready){for(const d of dots){const a=(now/2200+d.userData.k/4)%1;d.visible=p>.47;d.position.set(d.userData.x,vessel.position.y+1.9+5*a,d.userData.side*5.2)}redraw=true}
controls.update();if(redraw||playing){renderer.render(scene,camera);redraw=false}}
requestAnimationFrame(frame);
}catch(e){console.error(e);$('#loadtext').textContent=String(e.message||e);$('#retry').hidden=false;window.ATLAS_D={ready:false,error:String(e)}}
})();
